### ISSUE TITLE
vue 2.14以上版本不兼容 报Uncaught TypeError: _vm._v is not a function

### ISSUE THREAD

**Issue by zhangyanzt** [cookingjs/cooking-vue2#1]
应该跟之前ElementUI是一样的错误，锁定版本号后正常
"vue-template-compiler": "2.1.4"
"vue-loader": "10.0.0"
"vue": "2.1.4"

**Comment by QingWei-Li** [comment]
建议升级到最新

**Comment by zhangyanzt** [comment]
就是最新版才报的错

**Comment by QingWei-Li** [comment]
我正在写的项目就是用的最新版的 Vue，一切正常。麻烦提供可复现问题的 repo

**Comment by zhangyanzt** [comment]
参见  https://github.com/zhangyanzt/cooking-vue2-bug
直接用cooking init pages-vue 生成的项目，什么也没有改。
npm run dev
请求 http://localhost:8080/admin.html 页面空白
console打印出_vm._v is not a function

测试浏览器:Mac下Chrome与Firefox
Cooking版本:1.2.12
cooking-vue2版本:0.30

**Comment by QingWei-Li** [comment]
你用的是多页的那套模板，那套模板只是个示例，并不完善，Vue 用的是 CDN，在 app.json 文件里配置的

```js
"cdn": {
    "js": [
      "//unpkg.com/babel-polyfill@6.13.0/dist/polyfill.min.js",
      "//cdn.jsdelivr.net/vue/2.1.8/vue.min.js",
      "//cdn.jsdelivr.net/vuex/2.0.0/vuex.min.js"
    ],
    "css": []
  },
```

改成 2.1.8 一切正常

**Comment by zhangyanzt** [comment]
原来是在这里配的，谢谢。
